services:
  - type: web
    name: logimatch-api
    env: python
    region: oregon
    plan: free
    repo: https://github.com/donmckinney12/LogiMatch-AI
    branch: main
    rootDirectory: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///logimatch_v4.db
      - key: FLASK_ENV
        value: production
